---
# tasks file for redis_plugin

- name: Extract go1.17.3.linux-amd64.tar.gz into /usr/local
  unarchive:
    remote_src: yes
    src: https://storage.googleapis.com/golang/go1.17.3.linux-amd64.tar.gz
    dest: "{{ binary_path }}"
    owner: "{{ go_user }}"
    group: "{{ go_group }}"
    mode: 0755
  become: yes
    
- name: Add Go to PATH
  shell: export PATH=$PATH:/usr/local/go/bin

- name: Clone plugin repo
  git:
    repo: https://github.com/fhitchen/vault-plugin-database-redis
    dest: "{{ plugin_path }}"

- name: Create storage directories
  file:
    path: "{{ vault_plugins_path }}"
    state: directory

# TODO: Run Go commands, returns Permission denied atm
# - name: Build vault-redis plugin
#   command: chdir="{{ plugin_path }}" go build -o "{{ vault_plugins_path }}"/redis-database-plugin ./cmd/redis-database-plugin/

